[build]
# Enable auto-reload for all files
watch = ["src/**/*", "../ui-components/src/**/*"]
# Clear dist folder on rebuild
clean = true

[serve]
# Addresses to serve on
addresses = ["127.0.0.1"]
# Port to serve on
port = 3000
# Open the browser on server start
open = false 